{% set name = "python-lsp-server" %}
{% set version = "1.11.0" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89edd6fb3f7852e4bf5a3d1d95ea41484d1a28fa94b6e3cbff12b9db123b8e86

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

outputs:
  - name: {{ name|lower }}-base
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script: python -m pip install . --no-deps --no-build-isolation -vv
      entry_points:
        - pylsp = pylsp.__main__:main
    requirements:
      host:
        - python >=3.8
        - pip
        # Needed at build time to produce a package with the correct version for pip
        # See https://github.com/pypa/setuptools_scm/issues/636#issuecomment-1026435048
        - setuptools_scm >=3.4.3
      run:
        - python >=3.8
        - importlib_metadata >=4.8.3
        - jedi >=0.17.2,<0.20
        - python-lsp-jsonrpc >=1.1.0,<2.0.0
        - pluggy >=1.0.0
        - docstring-to-markdown
        - ujson >=3.0.0
    test:
      requires:
        - pip
      commands:
        - python -m pip check
        - pylsp --help
        # The pip version can be reported incorrectly if setuptools_scm isn't available
        # at build time.
        # Based on https://github.com/conda-forge/pyusb-feedstock/pull/4
        - pip list | grep -i python-lsp-server | grep {{ version }}

  - name: {{ name|lower }}
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
    requirements:
      host:
        - {{ pin_subpackage("python-lsp-server-base", exact=True) }}
        - python >=3.8
      run:
        - {{ pin_subpackage("python-lsp-server-base", exact=True) }}
        - autopep8 >=2.0.4,<2.1.0
        - flake8 >=7.0.0,<8.0.0
        - mccabe >=0.7.0,<0.8.0
        - pycodestyle >=2.11.0,<2.12.0
        - pydocstyle >=6.3.0,<6.4.0
        - pyflakes >=3.2.0,<3.3.0
        - pylint >=2.5.0,<3.1.0
        - rope >=1.11.0
        - whatthepatch >=1.0.2,<2.0.0
        - yapf >=0.33.0
    test:
      requires:
        - pip
      commands:
        - python -m pip check
        - pylsp --help
        # The pip version can be reported incorrectly if setuptools_scm isn't available
        # at build time.
        # Based on https://github.com/conda-forge/pyusb-feedstock/pull/4
        - pip list | grep -i python-lsp-server | grep {{ version }}

about:
  home: https://github.com/python-lsp/python-lsp-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 3.8+ implementation of the Language Server Protocol
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/python-lsp/python-lsp-server

extra:
  recipe-maintainers:
    - krassowski
    - ccordoba12
    - andfoy
    - steff456
    - dalthviz
